spring:
  application:
    name: kafka_sdk
server:
  port: 16943
# actuator metric
management.server.port: 16944
management.endpoint:metrics.enabled: true
management.endpoints.web.exposure.include: '*'
management.endpoint.prometheus.enabled: true
management.metrics.export.prometheus.enabled: true
management.endpoints.enabled-by-default: false
management.endpoint.info.enabled: true
management.endpoint.health.enabled: true
management.endpoint.metrics.enabled: true
management.endpoint.shutdown.enabled: true